### PR TITLE
feat: add type inference using zod model

### PR DESCRIPTION
**Pull request by sam-goodwin**
This change infers the type returned by a chat completion from the Zod model.

TypeScript's type system is (unsurprisingly) more powerful than Pythons. If we're going to build a TS-aligned chat library, there should be no need for users to explicitly annotate types like:

```ts
const user: User = await client.chat.completion.create ...
```

- [x] Infer type from ZodObject
- [x] Add `strictNullChecks: true` to tsconfig and fixed all the bugs
- [x] Pass through original Chat Completion Response if no response_model is provided

### CODE REVIEW

**Comment by jxnl** [comment]
Since the OpenAI SDK also uses snake case, we're keeping snake case in the arguments.

**Comment by jxnl** [comment]
maybe error out? or return the original response (python would be ok with this but this feels like breaking the types)

**Comment by sam-goodwin** [comment]
> maybe error out? or return the original response (python would be ok with this but this feels like breaking the types)

Updated code to pass through the Chat Completion response of no response_model is provided.

The return type will be inferred based on whether it is provided or not.

**Comment by sam-goodwin** [comment]
This error should be fixed now.

> Error: examples/resolving-complex-entitities/exampleGraphMaker.ts(45,21): error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.
> Error: Process completed with exit code 2.

**Pull request merged**
